// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Derived from SideStore apple-private-apis omnisette/src/lib.rs.
// Upstream repository: https://github.com/SideStore/apple-private-apis
// Upstream commit: 03beb1aa42991ccdad6214dee77e72282bef461f
// Modified by the Coffer project in 2026 to expose only loader-neutral local
// composition. The modified file remains MPL-2.0.

//! Local-only anisette composition derived from SideStore's `omnisette`.
//!
//! This private crate intentionally contains no native loader, HTTP transport,
//! automatic provisioning, runtime integration, feature flags, or provider
//! fallback. A caller supplies an [`AdiProxy`] implementation and explicitly
//! orchestrates provisioning outside this crate. Header retrieval only uses an
//! already provisioned proxy and otherwise returns [`AnisetteError::NotProvisioned`].

#![forbid(unsafe_code)]

mod adi_proxy;
mod anisette_headers_provider;

use core::fmt;

use sha2::{Digest as _, Sha256};
use thiserror::Error;
use zeroize::{Zeroize, ZeroizeOnDrop, Zeroizing};

pub use adi_proxy::{
    AdiError, AdiProxy, OtpMaterial, ProvisioningSession, ProvisioningStart, SecretBytes,
};
pub use anisette_headers_provider::{LocalAnisetteHeaders, LocalAnisetteProvider};

const MAX_HEADER_VALUE_BYTES: usize = 1_024;

/// Failure from local identity, proxy, or header composition.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
#[non_exhaustive]
pub enum AnisetteError {
    /// The proxy has no existing local provisioning state.
    #[error("local anisette state is not provisioned")]
    NotProvisioned,
    /// A helper-provided value was empty, oversized, or not printable ASCII.
    #[error("local anisette data was invalid")]
    InvalidData,
    /// The caller-supplied proxy rejected a local operation.
    #[error("local ADI operation failed")]
    Proxy(#[from] AdiError),
}

/// A printable, bounded value that is redacted and zeroized on drop.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct SecretString(Zeroizing<String>);

impl SecretString {
    /// Validates and takes ownership of a secret header or identity value.
    ///
    /// Values must be nonempty printable ASCII and at most 1,024 bytes. The
    /// input is zeroized on both success and error.
    ///
    /// # Errors
    ///
    /// Returns [`AnisetteError::InvalidData`] for an empty, oversized, or
    /// non-printable value.
    pub fn try_from_string(value: String) -> Result<Self, AnisetteError> {
        Self::try_from_zeroizing(Zeroizing::new(value))
    }

    fn try_from_zeroizing(value: Zeroizing<String>) -> Result<Self, AnisetteError> {
        if value.is_empty()
            || value.len() > MAX_HEADER_VALUE_BYTES
            || !value.bytes().all(|byte| matches!(byte, 0x20..=0x7e))
        {
            return Err(AnisetteError::InvalidData);
        }
        Ok(Self(value))
    }

    /// Exposes the value to the narrow caller that constructs request headers.
    #[must_use]
    pub fn expose_secret(&self) -> &str {
        self.0.as_str()
    }
}

impl fmt::Debug for SecretString {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("SecretString([REDACTED])")
    }
}

/// Identity values deterministically derived from one random 16-byte seed.
///
/// The input must be generated by a cryptographically secure random source and
/// persisted by the Coffer-owned state layer. This type performs no I/O or
/// random generation. It is move-only, redacts `Debug`, and zeroizes all
/// retained identity material on drop.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct DeviceIdentity {
    identifier: Zeroizing<[u8; 16]>,
    device_identifier: SecretString,
    local_user_id: SecretString,
    android_id: Zeroizing<[u8; 16]>,
}

impl DeviceIdentity {
    /// Derives the uppercase UUID, local user ID, and Android ID convention.
    ///
    /// The local user ID is uppercase hexadecimal SHA-256 of the raw seed. The
    /// Android ID is exactly the first 16 ASCII bytes of the uppercase UUID.
    #[must_use]
    pub fn from_random_identifier(identifier: [u8; 16]) -> Self {
        let device_identifier = format_uuid(identifier);
        let android_id = device_identifier.as_bytes()[..16]
            .try_into()
            .expect("the fixed UUID rendering is longer than 16 ASCII bytes");
        let mut digest: [u8; 32] = Sha256::digest(identifier).into();
        let local_user_id = encode_upper_hex(digest);
        digest.zeroize();
        Self {
            identifier: Zeroizing::new(identifier),
            device_identifier: SecretString::try_from_zeroizing(device_identifier)
                .expect("the fixed UUID rendering is printable and bounded"),
            local_user_id: SecretString::try_from_zeroizing(local_user_id)
                .expect("a SHA-256 hexadecimal digest is printable and bounded"),
            android_id: Zeroizing::new(android_id),
        }
    }

    /// Returns the raw seed for explicit persistence by the state owner.
    #[must_use]
    pub fn identifier(&self) -> &[u8; 16] {
        &self.identifier
    }

    /// Returns the uppercase UUID device identifier.
    #[must_use]
    pub fn device_identifier(&self) -> &SecretString {
        &self.device_identifier
    }

    /// Returns uppercase hexadecimal SHA-256 of the raw identifier.
    #[must_use]
    pub fn local_user_id(&self) -> &SecretString {
        &self.local_user_id
    }

    /// Returns the first 16 ASCII bytes of the uppercase UUID.
    #[must_use]
    pub fn android_id(&self) -> &[u8; 16] {
        &self.android_id
    }
}

impl fmt::Debug for DeviceIdentity {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("DeviceIdentity([REDACTED])")
    }
}

fn format_uuid(bytes: [u8; 16]) -> Zeroizing<String> {
    let hex = encode_upper_hex(bytes);
    Zeroizing::new(format!(
        "{}-{}-{}-{}-{}",
        &hex[0..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..32]
    ))
}

fn encode_upper_hex(bytes: impl AsRef<[u8]>) -> Zeroizing<String> {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    let bytes = bytes.as_ref();
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(char::from(HEX[usize::from(byte >> 4)]));
        encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    Zeroizing::new(encoded)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_derivation_is_byte_exact() {
        let identity = DeviceIdentity::from_random_identifier([
            0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd,
            0xee, 0xff,
        ]);
        assert_eq!(
            identity.device_identifier().expose_secret(),
            "00112233-4455-6677-8899-AABBCCDDEEFF"
        );
        assert_eq!(
            identity.local_user_id().expose_secret(),
            "A8FAED6ABBF35C12A4B26E40F6FEB19D736D90045C83B9F9A31F638D323E6811"
        );
        assert_eq!(identity.android_id(), b"00112233-4455-66");
    }

    #[test]
    fn secret_string_rejects_malformed_and_oversized_input() {
        assert!(matches!(
            SecretString::try_from_string(String::new()),
            Err(AnisetteError::InvalidData)
        ));
        assert!(matches!(
            SecretString::try_from_string("not-ascii-\u{80}".to_owned()),
            Err(AnisetteError::InvalidData)
        ));
        assert!(matches!(
            SecretString::try_from_string("x".repeat(MAX_HEADER_VALUE_BYTES + 1)),
            Err(AnisetteError::InvalidData)
        ));
    }

    #[test]
    fn secret_debug_is_redacted_and_zeroize_is_observable_internally() {
        let mut secret = SecretString::try_from_string("sensitive-marker".to_owned())
            .expect("valid test secret");
        assert_eq!(format!("{secret:?}"), "SecretString([REDACTED])");
        secret.zeroize();
        assert!(secret.0.is_empty());

        let identity = DeviceIdentity::from_random_identifier([7; 16]);
        assert_eq!(format!("{identity:?}"), "DeviceIdentity([REDACTED])");
    }
}
